### ISSUE TITLE
shit don't work :(

### ISSUE THREAD

**Issue by agogte** [agogte/calculator#1]
I tried various things, but the event listener isn't noticing the clicks on the buttons

**Comment by Bytebrkr** [comment]
document.addEventListener('DOMContentLoaded', function() {
    var screen = document.querySelector('.screen');
    var buttons = document.querySelectorAll('.buttons button');
  
    buttons.forEach(function(button) {
      button.addEventListener('click', function() {
        var buttonText = this.innerHTML;
  
        screen.innerHTML += buttonText;
      });
    });
  
    var equalsButton = document.getElementById('equals');
  
    equalsButton.addEventListener('click', function() {
      try {
        var result = eval(screen.innerHTML);
  
        screen.innerHTML = result;
      } catch (error) {
        screen.innerHTML = 'Error';
      }
    });
  
    var clearButton = document.getElementById('clear');
  
    clearButton.addEventListener('click', function() {
      screen.innerHTML = '';
    });
  });

**Comment by Bytebrkr** [comment]
`document.addEventListener('DOMContentLoaded', () => {
    const screen = document.querySelector('.screen');
    const buttons = document.querySelectorAll('.buttons button');
  
    buttons.forEach((button) => {
      button.addEventListener('click', () => {
        const buttonText = button.innerText;
        screen.innerText += buttonText;
      });
    });
  
    const equalsButton = document.getElementById('equals');
  
    equalsButton.addEventListener('click', () => {
      try {
        const expression = screen.innerText;
        const result = evaluateExpression(expression);
        screen.innerText = result;
      } catch (error) {
        screen.innerText = 'Error';
      }
    });
  
    const clearButton = document.getElementById('clear');
  
    clearButton.addEventListener('click', () => {
      screen.innerText = '';
    });
  });
  
  function evaluateExpression(expression) {
    let result;
    if (expression.includes('+')) {
      const operands = expression.split('+');
      result = parseFloat(operands[0]) + parseFloat(operands[1]);
    } else if (expression.includes('-')) {
      const operands = expression.split('-');
      result = parseFloat(operands[0]) - parseFloat(operands[1]);
    } else if (expression.includes('*')) {
      const operands = expression.split('*');
      result = parseFloat(operands[0]) * parseFloat(operands[1]);
    } else if (expression.includes('/')) {
      const operands = expression.split('/');
      result = parseFloat(operands[0]) / parseFloat(operands[1]);
    }
    return result;
  }
  `

**Comment by agogte** [comment]
Cool, thanks Luis. if this is prod ready, please open a PR
